services:
  edge:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/edge.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/certbot/www:/var/www/certbot
      - ./infra/certbot/conf:/etc/letsencrypt
    depends_on:
      - portfolio-web
      - boolcore-web
      - boolcore-api
    networks:
      - front
      - back

  portfolio-web:
    image: ${REGISTRY}/portfolio-web:${IMAGE_TAG}
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.portfolio
    restart: unless-stopped
    networks:
      - front

  boolcore-web:
    image: ${REGISTRY}/boolcore-web:${IMAGE_TAG}
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.boolcore-frontend
    restart: unless-stopped
    networks:
      - front

  boolcore-api:
    image: ${REGISTRY}/boolcore-api:${IMAGE_TAG}
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.boolcore-backend
    restart: unless-stopped
    environment:
      - GIN_MODE=release
      - PORT=8080
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
    networks:
      - back
  certbot:
    image: certbot/certbot:v2.11.0
    volumes:
      - ./infra/certbot/conf:/etc/letsencrypt
      - ./infra/certbot/www:/var/www/certbot

networks:
  front:
  back:
